# -*- coding: utf-8 -*-
"""Aula_1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1T50LrlRu84jTkLquQAm3KbCQHgcWCDJj
"""

import pandas as pd

df = pd.read_csv('/content/imigrantes_canada.csv')

df

df.info()

df.set_index('País', inplace=True)

anos = list(map(str, range(1980,2014)))

anos

brasil = df.loc['Brasil', anos]

brasil

brasil_dict = {'ano': brasil.index.tolist(), 'imigrantes' : brasil.values.tolist()}
dados_brasil = pd.DataFrame(brasil_dict)

dados_brasil

import matplotlib.pyplot as plt

plt.figure(figsize=(8,4))
plt.plot(dados_brasil['ano'], dados_brasil['imigrantes'])
plt.xticks(['1980', '1985', '1990', '1995', '2000', '2005', '2010'])
plt.yticks([500, 1000, 1500, 2000, 2500, 3000])
plt.show()

fig, ax = plt.subplots(figsize=(8,4))
ax.plot(dados_brasil['ano'], dados_brasil['imigrantes'], lw=4, color='g')
ax.set_title('Imigranção do Brasil para o Canadá\n1980 a 2013', fontsize=18, loc='left')
ax.set_xlabel('Ano', fontsize=14)
ax.set_ylabel('Imigrantes', fontsize=14)
ax.xaxis.set_tick_params(labelsize=12)
ax.yaxis.set_tick_params(labelsize=12)
ax.xaxis.set_major_locator(
plt.MultipleLocator(5))

ax.spines['top'].set_visible(False)
ax.spines['right'].set_visible(False)

fig.savefig('imigrantes_brasil_canada.png', dpi=300, bbox_inches='tight')

plt.show()

fig, axs = plt.subplots(1, 2, figsize=(8,4))

axs[0].plot(dados_brasil['ano'], dados_brasil['imigrantes'])
axs[0].set_title('Imigranção do Brasil para o Canadá\n1980 a 2013')
axs[0].set_xlabel('Ano')
axs[0].set_ylabel('Numero de Imigrantes')

axs[0].xaxis.set_major_locator(plt.MultipleLocator(5))
axs[0].grid()

axs[1].boxplot(dados_brasil['imigrantes'])
axs[1].set_title('Boxplot da Imigranção do Brasil para o Canadá\n1980 a 2013')
axs[1].set_xlabel('Brasil')
axs[1].set_ylabel('Numero de Imigrantes')
axs[1].grid()

plt.show()

dados_brasil.describe()

# Criando a figura
fig, axs = plt.subplots(2, 2, figsize=(10, 6))

# Subplots
axs[0, 0].plot(df.loc['Brasil', anos])
axs[0, 0].set_title('Brasil')

axs[0, 1].plot(df.loc['Colômbia', anos])
axs[0, 1].set_title('Colômbia')

axs[1, 0].plot(df.loc['Argentina', anos])
axs[1, 0].set_title('Argentina')

axs[1, 1].plot(df.loc['Peru', anos])
axs[1, 1].set_title('Peru')

plt.show()

# Criando a figura
fig, axs = plt.subplots(2, 2, figsize=(10, 6))

# Ajustando o espaçamento
fig.subplots_adjust(hspace=0.5, wspace=0.3)

# Subplots
axs[0, 0].plot(df.loc['Brasil', anos])
axs[0, 0].set_title('Brasil')

axs[0, 1].plot(df.loc['Colômbia', anos])
axs[0, 1].set_title('Colômbia')

axs[1, 0].plot(df.loc['Argentina', anos])
axs[1, 0].set_title('Argentina')

axs[1, 1].plot(df.loc['Peru', anos])
axs[1, 1].set_title('Peru')

plt.show()

# Criando a figura
fig, axs = plt.subplots(2, 2, figsize=(10, 6))

# Ajustando o espaçamento
fig.subplots_adjust(hspace=0.5, wspace=0.3)

# Subplots
axs[0, 0].plot(df.loc['Brasil', anos])
axs[0, 0].set_title('Brasil')

axs[0, 1].plot(df.loc['Colômbia', anos])
axs[0, 1].set_title('Colômbia')

axs[1, 0].plot(df.loc['Argentina', anos])
axs[1, 0].set_title('Argentina')

axs[1, 1].plot(df.loc['Peru', anos])
axs[1, 1].set_title('Peru')

# Alterando a frequência dos ticks do eixo X em todos os subplots
for ax in axs.flat:
    ax.xaxis.set_major_locator(plt.MultipleLocator(5))

plt.show()

# Criando a figura
fig, axs = plt.subplots(2, 2, figsize=(10, 6))

# Ajustando o espaçamento
fig.subplots_adjust(hspace=0.5, wspace=0.3)

# Subplots
axs[0, 0].plot(df.loc['Brasil', anos])
axs[0, 0].set_title('Brasil')

axs[0, 1].plot(df.loc['Colômbia', anos])
axs[0, 1].set_title('Colômbia')

axs[1, 0].plot(df.loc['Argentina', anos])
axs[1, 0].set_title('Argentina')

axs[1, 1].plot(df.loc['Peru', anos])
axs[1, 1].set_title('Peru')

# Alterando a frequência dos ticks do eixo X em todos os subplots
for ax in axs.flat:
    ax.xaxis.set_major_locator(plt.MultipleLocator(5))

# Adicionando rótulos para os eixos X e Y
for ax in axs.flat:
    ax.set_xlabel('Ano')
    ax.set_ylabel('Número de imigrantes')

plt.show()

# Criando a figura
fig, axs = plt.subplots(2, 2, figsize=(10, 6))

# Ajustando o espaçamento
fig.subplots_adjust(hspace=0.5, wspace=0.3)

# Subplots
axs[0, 0].plot(df.loc['Brasil', anos])
axs[0, 0].set_title('Brasil')

axs[0, 1].plot(df.loc['Colômbia', anos])
axs[0, 1].set_title('Colômbia')

axs[1, 0].plot(df.loc['Argentina', anos])
axs[1, 0].set_title('Argentina')

axs[1, 1].plot(df.loc['Peru', anos])
axs[1, 1].set_title('Peru')

# Alterando a frequência dos ticks do eixo X em todos os subplots
for ax in axs.flat:
    ax.xaxis.set_major_locator(plt.MultipleLocator(5))

# Adicionando rótulos para os eixos X e Y
for ax in axs.flat:
    ax.set_xlabel('Ano')
    ax.set_ylabel('Número de imigrantes')

# Definindo a mesma escala no eixo Y em todos os subplots
ymin = 0
ymax = 7000
for ax in axs.ravel():
    ax.set_ylim(ymin, ymax)

plt.show()

# Criando a figura
fig, axs = plt.subplots(2, 2, figsize=(10, 6))

# Ajustando o espaçamento
fig.subplots_adjust(hspace=0.5, wspace=0.3)

# Adicionando um título geral para os subplots
fig.suptitle('Imigração dos quatro maiores países da América do Sul para o Canadá de 1980 a 2013')
# Subplots
axs[0, 0].plot(df.loc['Brasil', anos])
axs[0, 0].set_title('Brasil')

axs[0, 1].plot(df.loc['Colômbia', anos])
axs[0, 1].set_title('Colômbia')

axs[1, 0].plot(df.loc['Argentina', anos])
axs[1, 0].set_title('Argentina')

axs[1, 1].plot(df.loc['Peru', anos])
axs[1, 1].set_title('Peru')

# Alterando a frequência dos ticks do eixo X em todos os subplots
for ax in axs.flat:
    ax.xaxis.set_major_locator(plt.MultipleLocator(5))

# Adicionando rótulos para os eixos X e Y
for ax in axs.flat:
    ax.set_xlabel('Ano')
    ax.set_ylabel('Número de imigrantes')

# Definindo a mesma escala no eixo Y em todos os subplots
ymin = 0
ymax = 7000
for ax in axs.ravel():
    ax.set_ylim(ymin, ymax)

plt.show()

df.head()

america_sul = df.query('Região == "América do Sul"')

america_sul

cores = []

for pais in america_sul_sorted.index:
    if pais == 'Brasil' :
        cores.append('green')
    else:
        cores.append('silver')

fig, ax = plt.subplots(figsize=(12,5))
ax.barh(america_sul_sorted.index, america_sul_sorted['Total'], color=cores)
ax.set_title('Brasil foi o 4 pais com mais imigrantres\n para o Canadá no peripodo de 1980 a 2013', fontsize=18, loc='left')
ax.set_ylabel('')
ax.set_xlabel(' Numero de Imigrantes', fontsize=14)
ax.xaxis.set_tick_params(labelsize=12)
ax.yaxis.set_tick_params(labelsize=12)


for i,v in enumerate(america_sul_sorted['Total']):
  ax.text(v + 20, i, str(v), color='black', fontsize=10, ha='left', va='center')

  ax.set_frame_on(False)
  ax.get_xaxis().set_visible(False)
  ax.tick_params(axis='both', which='both', length=0)

  fig.savefig('imigrantes_america_sul.png', dpi=300, bbox_inches='tight')
plt.show()



america_sul_sorted = america_sul.sort_values('Total', ascending=False)

print(fig.canvas.get_supported_filetypes())

import seaborn as sns

sns.set_theme()

top_10 = df.sort_values('Total', ascending=False).head(10)

top_10

sns.barplot(data=top_10, x=top_10.index, y='Total')

sns.barplot(data=top_10, y=top_10.index, x='Total', palette='rocket')

# Criando a figura
fig, ax = plt.subplots(figsize=(8,4))
ax=sns.barplot(data=top_10, y=top_10.index, x='Total', orient='h')

# Personalizando o gráfico
ax.set_title('Países com maior imigração para o Canadá\n1980 a 2013', loc='left', fontsize=16)
ax.set_xlabel('Número de imigrantes', fontsize=14)
ax.set_ylabel('')

# Exibindo o gráfico
plt.show()

def gerar_grafico_paleta(palette):
    fig, ax = plt.subplots(figsize=(8,4))
    ax = sns.barplot(data=top_10, y=top_10.index, x='Total', orient='h', palette=palette)
    ax.set_title('Países com maior imigração para o Canadá\n1980 a 2013', loc='left', fontsize=16)
    ax.set_xlabel('Número de imigrantes', fontsize=14)
    ax.set_ylabel('')
    plt.show()

gerar_grafico_paleta('Blues')

gerar_grafico_paleta('Blues_r')

gerar_grafico_paleta('rocket')

gerar_grafico_paleta('coolwarm')

gerar_grafico_paleta('coolwarm')

# Alterando o tema
sns.set_theme(style='dark')

# Gerando o gráfico
gerar_grafico_paleta('tab10')

# Alterando o tema
sns.set_theme(style='whitegrid')

# Gerando o gráfico
gerar_grafico_paleta('tab10')

# Alterando o tema
sns.set_theme(style='white')

# Gerando o gráfico
gerar_grafico_paleta('tab10')

# Alterando o tema
sns.set_theme(style='ticks')

# Gerando o gráfico
gerar_grafico_paleta('tab10')

#Criando a figura
fig, ax = plt.subplots(figsize=(8,4))
sns.barplot(data=top_10, y=top_10.index, x='Total', orient='h', palette='tab10')

# Personalizando
ax.set_title('Países com maior imigração para o Canadá\n1980 a 2013', loc='left', fontsize=16)
ax.set_xlabel('Número de imigrantes', fontsize=14)
ax.set_ylabel('')
sns.despine()

plt.show()

import plotly.express as px

from os import XATTR_CREATE
fig = px.line(dados_brasil, x='ano', y='imigrantes')
fig.update_layout(width=1000, height=500,
                  xaxis={'tickangle':-45})
fig.show()

fig = px.line(dados_brasil, x='ano', y='imigrantes',
              title='Imigração dos Brasil para o Canadá no período de 1980 a 2013')
fig.update_layout(width=1000, height=500,
                  xaxis={'tickangle': -45})
fig.show()

fig = px.line(dados_brasil, x='ano', y='imigrantes',
              title='Imigração do Brasil para o Canadá no período de 1980 a 2013')
fig.update_layout(
    width=1000, height=500,
    xaxis={'tickangle': -45},
    xaxis_title='Ano',
    yaxis_title='Número de imigrantes')

fig.show()

fig = px.line(dados_brasil, x='ano', y='imigrantes',
              title='Imigração do Brasil para o Canadá no período de 1980 a 2013')
fig.update_layout(
    width=1000, height=500,
    xaxis={'tickangle': -45},
    font_family='Arial',
    font_size=14,
    font_color='grey',
    title_font_color='black',
    title_font_size=22,
    xaxis_title='Ano',
    yaxis_title='Número de imigrantes')
fig.show()

america_sul.head()

df_america_sul_clean = america_sul.drop(['Continente', 'Região', 'Total'], axis=1)
america_sul_final = df_america_sul_clean.T

america_sul_final.head()

fig = px.line(america_sul_final, x=america_sul_final.index, y=america_sul_final.columns, color='País',
              title='Imigração dos países da América do Sul para o Canadá de 1980 a 2013')
fig.update_layout(
    xaxis={'tickangle': -45},
    xaxis_title='Ano',
    yaxis_title='Número de imigrantes')

fig.show()

fig = px.line(america_sul_final, x=america_sul_final.index, y=america_sul_final.columns, color='País', markers=True,
              title='Imigração dos países da América do Sul para o Canadá de 1980 a 2013')
fig.update_layout(
    xaxis={'tickangle': -45},
    xaxis_title='Ano',
    yaxis_title='Número de imigrantes')

fig.show()

fig.write_html('imigracao_america_sul.html')